apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: ivolve
spec:
  selector:
    app: my-app     # ← خليه زي ما هو موجود في البود
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
