plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  instance-state-name: running
  tag:Project: CloudDevOpsProject

keyed_groups:
  - key: tags.Role
    prefix: ""
    separator: ""

compose:
  ansible_host: >
    {{
      (tags.Role == "Jenkins-Slave") | ternary(private_ip_address, public_ip_address)
    }}

vars:
  ansible_user: ec2-user
  ansible_ssh_private_key_file: /root/CloudDevOpsProject/terraform/CloudDevOpsProject-keypair.pem
